os: linux
dist: bionic
language: c

compiler:
  - gcc

git:
  submodules: false
  depth: 3

before_install:
  - sudo apt-get update && sudo apt-get -y install dos2unix libboost-all-dev texinfo texi2html libxml2-dev subversion bison flex zlib1g-dev
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:
  - wget https://github.com/vipoo/z88dk/releases/download/v2.0.0-dino/z88dk-2.0.0-dino.tar.gz
  - mkdir -p z88dk
  - tar -xzvf z88dk-2.0.0-dino.tar.gz -C ./z88dk/
  - make cpm

before_script:
  - export PATH=`pwd`/z88dk/bin:$PATH
  - export ZCCCFG=`pwd`/z88dk/lib/config

script:
  - make
  - make test

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: bbcbasic.com
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false