
;
;LIST OF TOKENS AND KEYWORDS.
;IF A KEYWORD IS FOLLOWED BY NUL THEN IT WILL
; ONLY MATCH WITH THE WORD FOLLOWED IMMEDIATELY
; BY A DELIMITER.
;
include "constants.inc"

	PUBLIC	KEYWDS, KEYWDL, ERRWDS
	EXTERN 	TK_EXTENDED, TKX_EXEC_FIRST, TKX_EVAL_FIRST, TKN_FIRSTCMD

	PUBLIC	TKR_AND, TKR_DIV, TKR_EOR, TKR_MOD, TKR_OR
	PUBLIC	TKR_LINE, TK_TOKLO, TK_TOKHI, TK_OFFSET, TKR_THEN, TKR_ELSE, TKR_ERROR, TKR_STEP, TKR_SPC, TKR_TAB, TKR_OFF
	EXTERN	TKE_TOPV


#define TKN_DEF_OP EXTERN TKN_#1 !
	DEFM	TKN_#1, "#1"

#define TKN_DEF_OP_ALIAS EXTERN TKN_#2	!
	DEFM	TKN_#2, "#1"

#define TKN_DEF_ST EXTERN TKN_#1 !
	DEFM	TKN_#1, "#1", 0

#define TKN_DEF_ST_ALIAS EXTERN TKN_#2 !
	DEFM	TKN_#2, "#1", 0

#define TKE_DEF_OP EXTERN TKE_#1 !
	DEFM	TKE_#1, "#1"

#define TKE_DEF_OP_ALIAS EXTERN TKE_#2	!
	DEFM	TKE_#2, "#1"

#define TKE_DEF_ST EXTERN TKE_#1 !
	DEFM	TKE_#1, "#1", 0

#define TKE_DEF_ST_ALIAS EXTERN TKE_#2 !
	DEFM	TKE_#2, "#1", 0

TKX_EVAL_FIRST	EQU	'a'
TKX_EXEC_FIRST	EQU	'A'

TKX_IN		EQU	TKX_EVAL_FIRST + 0
TKX_OSCLI	EQU	TKX_EXEC_FIRST + 0
TKX_OUT		EQU	TKX_EXEC_FIRST + 1

KEYWDS:	DEFM	TKR_AND, 	"AND"
	TKE_DEF_OP(ABS)
	TKE_DEF_OP(ACS)
	TKE_DEF_OP(ADVAL)
	TKE_DEF_OP(ASC)
	TKE_DEF_OP(ASN)
	TKE_DEF_OP(ATN)
	TKN_DEF_OP(AUTO)
	TKE_DEF_ST(BGET)
	TKN_DEF_ST(BPUT)
	TKN_DEF_OP(COLOUR)
	TKN_DEF_OP_ALIAS(COLOR,COLOUR)
	TKN_DEF_OP(CALL)
	TKN_DEF_OP(CHAIN)
	TKE_DEF_OP_ALIAS(CHR$,CHRS)
	TKN_DEF_ST_ALIAS(CLEAR,CLR)
	TKN_DEF_ST(CLOSE)
	TKN_DEF_ST(CLG)
	TKN_DEF_ST(CLS)
	TKE_DEF_OP(COS)
	TKE_DEF_ST_ALIAS(COUNT,COUNTV)
	TKN_DEF_OP(DATA)
	TKE_DEF_OP(DEG)
	TKN_DEF_OP(DEF)
	TKN_DEF_OP(DELETE)
	DEFM	TKR_DIV, "DIV"
	TKN_DEF_OP(DIM)
	TKN_DEF_OP(DRAW)
	TKN_DEF_ST_ALIAS(ENDPROC,ENDPRO)
	TKN_DEF_ST(END)
	TKN_DEF_OP_ALIAS(ENVELOPE,ENVEL)
	DEFM	TKR_ELSE, "ELSE"
	TKE_DEF_OP(EVAL)
	TKE_DEF_ST_ALIAS(ERL,ERLV)
	DEFM	TKR_ERROR, "ERROR"
	TKE_DEF_ST(EOF)
	DEFM	TKR_EOR, "EOR"
	TKE_DEF_ST_ALIAS(ERR,ERRV)
	TKE_DEF_OP(EXP)
	TKE_DEF_ST(EXT)
	TKN_DEF_OP(FOR)
	TKE_DEF_ST_ALIAS(FALSE,ZERO)
	TKE_DEF_OP(FN)
	TKN_DEF_OP(GOTO)
	TKE_DEF_OP_ALIAS(GET$,GETS)
	TKE_DEF_OP(GET)
	TKN_DEF_OP(GOSUB)
	TKN_DEF_OP(GCOL)
	TKE_DEF_ST_ALIAS(HIMEM,HIMEMV)
	TKN_DEF_OP(INPUT)
	TKN_DEF_OP(IF)
	TKE_DEF_OP_ALIAS(INKEY$,INKEYS)
	TKE_DEF_OP(INKEY)
	TKE_DEF_OP(INT)
	DEFM	TK_EXTENDED, TKX_IN, "INP("
	DEFM	TK_EXTENDED, TKX_IN, "IN("
	TKE_DEF_OP_ALIAS(INSTR!(,INSTR)
	TKN_DEF_OP(LIST)
	DEFM	TKR_LINE, "LINE"
	TKN_DEF_OP(LOAD)
	TKE_DEF_ST_ALIAS(LOMEM,LOMEMV)
	TKN_DEF_OP(LOCAL)
	TKE_DEF_OP_ALIAS(LEFT$!(,LEFTS)
	TKE_DEF_OP(LEN)
	TKN_DEF_OP(LET)
	TKE_DEF_OP(LOG)
	TKE_DEF_OP(LN)
	TKE_DEF_OP_ALIAS(MID$!(,MIDS)
	TKN_DEF_OP(MODE)
	DEFM	TKR_MOD, "MOD"
	TKN_DEF_OP(MOVE)
	TKN_DEF_OP(NEXT)
	TKN_DEF_ST(NEW)
	TKE_DEF_OP(NOT)
	TKN_DEF_ST(OLD)
	TKN_DEF_OP(ON)
	DEFM	TKR_OFF, "OFF"
	DEFM	TKR_OR, "OR"
	TKE_DEF_OP(OPENIN)
	TKE_DEF_OP_ALIAS(OPENOUT,OPENOT)
	TKE_DEF_OP(OPENUP)
	DEFM	TK_EXTENDED, TKX_OSCLI, "OSCLI"
	DEFM	TK_EXTENDED, TKX_OUT, "OUT"
	TKN_DEF_OP(PRINT)
	TKE_DEF_ST_ALIAS(PAGE,PAGEV)
	TKE_DEF_ST(PTR)
	TKE_DEF_ST(PI)
	TKN_DEF_OP(PLOT)
	TKE_DEF_OP_ALIAS(POINT!(,POINT)
	TKN_DEF_OP(PROC)
	TKE_DEF_ST(POS)
	TKN_DEF_OP(PUT)
	TKN_DEF_ST(RETURN)
	TKN_DEF_OP(REPEAT)
	TKN_DEF_ST_ALIAS(REPORT,REPOR)
	TKN_DEF_OP(READ)
	TKN_DEF_OP(REM)
	TKN_DEF_ST(RUN)
	TKE_DEF_OP(RAD)
	TKN_DEF_OP_ALIAS(RESTORE,RESTOR)
	TKE_DEF_OP_ALIAS(RIGHT$!(,RIGHTS)
	TKE_DEF_ST(RND)
	TKN_DEF_OP(RENUMBER)
	DEFM	TKR_STEP, "STEP"
	TKN_DEF_OP(SAVE)
	TKE_DEF_OP(SGN)
	TKE_DEF_OP(SIN)
	TKE_DEF_OP(SQR)
	DEFM	TKR_SPC, "SPC"
	TKE_DEF_OP_ALIAS(STR$,STRS)
	TKE_DEF_OP_ALIAS(STRING$!(,STRING)
	TKN_DEF_OP(SOUND)
	TKN_DEF_ST(STOP)
	TKE_DEF_OP(TAN)
	DEFM	TKR_THEN, "THEN"
	TKE_DEF_OP_ALIAS(TO,TOPV)
	DEFM	TKR_TAB, "TAB("
	TKN_DEF_OP(TRACE)
	TKE_DEF_ST_ALIAS(TIME,TIMEV)
	TKE_DEF_ST(TRUE)
	TKN_DEF_OP(UNTIL)
	TKE_DEF_OP(USR)
	TKN_DEF_OP(VDU)
	TKE_DEF_OP(VAL)
	TKE_DEF_ST(VPOS)
	TKN_DEF_OP_ALIAS(WIDTH,WIDTHV)
	TKN_DEF_OP_ALIAS(HIMEM,HIMEMV)
	TKN_DEF_OP_ALIAS(LOMEM,LOMEMV)
	TKN_DEF_OP_ALIAS(PAGE,PAGEV)
	TKN_DEF_OP(PTR)
	TKN_DEF_OP_ALIAS(TIME,TIMEV)
	DEFB	1
	DEFM	"Missing "
	DEFB	2
	DEFM	"No such "
	DEFB	3
	DEFM	"Bad "
	DEFB	4
	DEFM	" range"
	DEFB	5
	DEFM	"variable"
	DEFB	6
	DEFM	"Out of"
	DEFB	7
	DEFM	"No "
	DEFB	8
	DEFM	" space"

KEYWDSEND:
KEYWDL	EQU	KEYWDSEND - KEYWDS

	DEFW	-1


TKR_AND		EQU	80H
TKR_DIV		EQU	81H
TKR_EOR		EQU	82H
TKR_MOD		EQU	83H
TKR_OR		EQU	84H
TKR_ERROR	EQU	85H
TKR_LINE	EQU	86H
TKR_OFF		EQU	87H
TKR_STEP	EQU	88H
TKR_SPC		EQU	89H
TKR_TAB		EQU	8AH
TKR_ELSE	EQU	8BH
TKR_THEN	EQU	8CH

TK_TOKLO	EQU	TKE_PAGEV - 1 ; 8FH
TK_TOKHI	EQU	TKE_HIMEMV	; 93H
TK_OFFSET	EQU	(TKN_PAGEV - 1) - TK_TOKLO ;	0CFH - TK_TOKLO

TK_EXTENDED	EQU	$FF
;
;ERROR MESSAGES:
;
ERRWDS:	DEFB	7
	DEFM	"room"
	DEFB	0
	DEFB	6
	DEFB	4
	DEFB	0
	DEFW	0
	DEFM	"Mistake"
	DEFB	0
	DEFB	1
	DEFM	","
	DEFB	0
	DEFM	"Type mismatch"
	DEFB	0
	DEFB	7
	DEFB	TKE_FN
	DEFW	0
	DEFB	1
	DEFM	DOUBLE_QUOTE
	DEFB	0
	DEFB	3
	DEFB	TKN_DIM
	DEFB	0
	DEFB	TKN_DIM
	DEFB	8
	DEFB	0
	DEFM	"Not "
	DEFB	TKN_LOCAL
	DEFB	0
	DEFB	7
	DEFB	TKN_PROC
	DEFB	0
	DEFM	"Array"
	DEFB	0
	DEFM	"Subscript"
	DEFB	0
	DEFM	"Syntax error"
	DEFB	0
	DEFM	"Escape"
	DEFB	0
	DEFM	"Division by zero"
	DEFB	0
	DEFM	"String too long"
	DEFB	0
	DEFM	"Too big"
	DEFB	0
	DEFM	"-ve root"
	DEFB	0
	DEFM	"Log"
	DEFB	4
	DEFB	0
	DEFM	"Accuracy lost"
	DEFB	0
	DEFM	"Exp"
	DEFB	4
	DEFW	0
	DEFB	2
	DEFB	5
	DEFB	0
	DEFB	1
	DEFM	")"
	DEFB	0
	DEFB	3
	DEFM	"HEX"
	DEFB	0
	DEFB	2
	DEFB	TKE_FN
	DEFM	"/"
	DEFB	TKN_PROC
	DEFB	0
	DEFB	3
	DEFM	"call"
	DEFB	0
	DEFM	"Arguments"
	DEFB	0
	DEFB	7
	DEFB	TKN_FOR
	DEFB	0
	DEFM	"Can't match "
	DEFB	TKN_FOR
	DEFB	0
	DEFB	TKN_FOR
	DEFM	" "
	DEFB	5
	DEFW	0
	DEFB	7
	DEFB	TKE_TOPV
	DEFW	0
	DEFB	7
	DEFB	TKN_GOSUB
	DEFB	0
	DEFB	TKN_ON
	DEFM	" syntax"
	DEFB	0
	DEFB	TKN_ON
	DEFB	4
	DEFB	0
	DEFB	2
	DEFM	"line"
	DEFB	0
	DEFB	6
	DEFM	" "
	DEFB	TKN_DATA
	DEFB	0
	DEFB	7
	DEFB	TKN_REPEAT
	DEFW	0
	DEFB	1
	DEFM	"#"
	DEFB	0
