
BDOS	EQU	5

IFDEF TRACING

	PUBLIC	PRTSTRZ
	PUBLIC	PRTHEX
	PUBLIC	PRTHEXWORDDE
	PUBLIC	PRTHEXWORDBC
	PUBLIC	PRTHEXWORDHL
	PUBLIC	NEWLINE
	PUBLIC	PRTCHR
	PUBLIC	PRTSTRD

PRTSTRD:
	EX	(SP),HL
	PUSH	AF
	CALL	PRTSTRZ
	POP	AF
	EX	(SP),HL
	RET

;===============================================================================
; PRINT A $ TERMINATED STRING AT (HL) WITHOUT DESTROYING ANY REGISTERS
PRTSTRZ:
	LD	A, (HL)			; GET NEXT CHAR
	INC	HL
	CP	'$'
	RET	Z
	CALL	PRTCHR
	JR	PRTSTRZ
;
; PRINT THE HEX WORD VALUE IN HL
;
PRTHEXWORDHL:
	PUSH	AF
	LD	A,H
	CALL	PRTHEX
	LD	A,L
	CALL	PRTHEX
	POP	AF
	RET

PRTHEXWORDDE:
	PUSH	HL
	PUSH	DE
	PUSH	DE
	POP	HL
	CALL 	PRTHEXWORDHL
	POP 	DE
	POP	HL
	RET

PRTHEXWORDBC:
	PUSH	BC
	PUSH	BC
	POP	HL
	CALL	PRTHEXWORDHL
	POP	BC
	RET

PRTCHR:
	PUSH	AF
	PUSH	IY
	PUSH	BC			; SAVE REGISTERS
	PUSH	DE
	PUSH	HL
	LD	E, A			; CHARACTER TO PRINT IN E
	LD	C, $02			; BDOS FUNCTION TO OUTPUT A CHARACTER
	CALL	BDOS			; DO IT
	POP	HL			; RESTORE REGISTERS
	POP	DE
	POP	BC
	POP	IY
	POP	AF
	RET

PRTHEX:
	PUSH	AF			; SAVE AF
	PUSH	DE			; SAVE DE
	CALL	HEXASCII		; CONVERT VALUE IN A TO HEX CHARS IN DE
	LD	A, D			; GET THE HIGH ORDER HEX CHAR
	CALL	PRTCHR			; PRINT IT
	LD	A, E			; GET THE LOW ORDER HEX CHAR
	CALL	PRTCHR			; PRINT IT
	POP	DE			; RESTORE DE
	POP	AF			; RESTORE AF
	RET				; DONE

HEXASCII:
	LD	D, A			; SAVE A IN D
	CALL	HEXCONV			; CONVERT LOW NIBBLE OF A TO HEX
	LD	E, A			; SAVE IT IN E
	LD	A, D			; GET ORIGINAL VALUE BACK
	RLCA				; ROTATE HIGH ORDER NIBBLE TO LOW BITS
	RLCA
	RLCA
	RLCA
	CALL	HEXCONV			; CONVERT NIBBLE
	LD	D, A			; SAVE IT IN D
	RET				; DONE

;===============================================================================
; CONVERT LOW NIBBLE OF A TO ASCII HEX

HEXCONV:
	AND	$0F	     		; LOW NIBBLE ONLY
	ADD	A, $90
	DAA
	ADC	A, $40
	DAA
	RET

;===============================================================================
; START A NEW LINE

NEWLINE:
	PUSH	AF
	LD	A, 13			; <CR>
	CALL	PRTCHR			; PRINT IT
	LD	A, 10			; <LF>
	CALL	PRTCHR			; PRINT IT
	POP	AF
	RET

ENDIF ; IFDEF TRACING
